### ISSUE TITLE
[#dshawaf4] Dev Related on ServiceWorkers

### ISSUE THREAD

**Issue by dshaw** [dshaw/alwaysforward#13]
## Title

Always Forward with dshaw: Dev Related on ServiceWorkers

## Topic

ServiceWorkers are changing the execution model of the web platform and are at the heart of PWAs. We'll explore how they are being used today and how Node.js can align with the web platform by bringing the ServiceWorker model to the server-side.

## Participant(s)

* Dan Shaw - @dshaw - Strategic Advisor
* Tara Z. Manicsic - @tzmanics - Developer Advocate at Progress, Google Developer Expert
* Jake Archibald - @jakearchibald - Google
* Patrick Kettner - @patrickkettner - Microsoft

CANDIDATES:
* Jake Archibald - @jakearchibald - Google
* Anna Henningsen - @addaleax - Node.js Core Contributor
* Matt Gaunt - @gauntface - Google
* Patrick Kettner - @patrickkettner - Microsoft
* Simon MacDonald - @macdonst - Adobe

## Schedule

Live Monday, APR 9, 2018 at 10am PT on [Crowdcast](https://www.crowdcast.io/dshaw) - Note the non-standard day. _Tuesday is pub quiz night._ 🍻:sparkles:

## Agenda

_Part 1 - High Level_

- Opening thoughts on Node.js and the Web Platform with dshaw
[dshaw and tzmanics switch screens for tzmanics to guest host]

- Describe PWAs [patrickkettner]
- Describe Service Workers [gauntface]
- Describe Cache API [jakearchibald]

**:20 Ad slot #1 - Woebot**

_Part 2 - Today’s Service Workers_

**Questions from [Twitter](https://twitter.com/Tzmanics/status/982391453719711744)**

- What are some of the best practices that each of you go by? Resources for best practices?
- Beyond the fact that SW are served over HTTPS what other insights can you offer about the security of using SWs?
- Tips and Warnings about Caching
- What happened to periodic synchronization?

**Backup Topics**
- Where are the roadblocks with Service Workers today?
- Caching per browser comparisons
- Store timeline, bringing apps into the store?
- Safari on iOS support?
- Using the browser to prompt user to install
- Service Worker lifecycle

**:40 Ad slot #2 - Operation Code**

_Part 3 - Q&A and Looking Forward_

- What’s your perspective on Node.js and Service Workers?
- Audience questions
- Closing thoughts with dshaw

## Transcript

Not available

## Sponsors

* [Woebot](https://woebot.io/?r=dshawaf) - Mental health impacts us all. [https://woebot.io/jobs](https://woebot.io/jobs).

## Link(s)

* Episode live url: https://www.crowdcast.io/e/dshawaf4

## Meta

#dshawaf4 #dshawaf #AlwaysForward #nodejs #devrelated #woebot

**Comment by jakearchibald** [comment]
Any chance we can make this the 4th, 5th, 6th or 9th?

**Comment by tzmanics** [comment]
We're hoping to try to keep episodes consistently on a Tuesday 😸 . With that in mind, does Tuesday, March 27 work for you two (@addaleax & @jakearchibald)?

**Comment by jakearchibald** [comment]
Unfortunately Tuesday evening is pub quiz night for me 😄.

**Comment by tzmanics** [comment]
Quiz night! 😍
Well in that case let's go ahead and do it 4/9. I'll send out a calendar invite to hold the spot so none of us have to use those memory things ;)

**Comment by dshaw** [comment]
@patrickkettner Glad to hear you'll be joining us.

**Comment by patrickkettner** [comment]
👋- really looking forward to it :D

**Comment by gauntface** [comment]
I'm only just seeing this, *sorry*, but happy to join if you want moar people to join.

**Comment by tzmanics** [comment]
Hi all! Here is the rundown we have for the episode. Please let us know if you would like anything changed/added.

We have a tweet out to get community feedback on questions if you'd like to share it: https://bit.ly/2JspCkS We have backup questions for now but will replace them depending on how the twittersphere responds.

Looking forward to chatting with you all!

**Episode Details:**

_Part 1 - High Level_

- Opening thoughts on Node.js and the Web Platform with dshaw
[dshaw and tzmanics switch screens for tzmanics to guest host]

-  Describe PWAs [patrickkettner]
-  Describe Service Workers [gauntface]
-  Describe Cache API [jakearchibald]

:20 Ad slot #1 - Woebot

_Part 2 - Today’s Service Workers_

[Questions from Twitter || these backup topics]

- Where are the roadblocks with Service Workers today?
- Caching per browser comparisons
- Store timeline, bringing apps into the store?
- Best practices and resources
- Safari on iOS support?
- Using the browser to prompt user to install
- Service Worker lifecycle

:40 Ad slot #2 - Operation Code

_Part 3 - Q&A and Looking Forward_

- What’s your perspective on Node.js and Service Workers?
- Audience questions
- Closing thoughts with dshaw

**Comment by dshaw** [comment]
Exciting update: Worker support is close to landing in Node.js! https://github.com/nodejs/node/pull/20876
