### ISSUE TITLE
[#dshawaf6] Dev Related on Modules

### ISSUE THREAD

**Issue by tzmanics** [dshaw/alwaysforward#18]
## Title
Always Forward with dshaw: Dev Related on Modules

## Topic

Modules have given us the ability to reuse code and most developers use them every day. How much do we know and understand about the current modules system we use and the changes that need to be made?  Currently, we have two ways of handling modules: the CommonJS modules system (CJM) and the ECMAScript Module system (ESM). When using Node and when programming for the web we have been using CJM for years but the shift to ESM is happening. 

In this podcast, we'll discuss the history of how we got to these non-compatible systems, the steps the Node Modules Working Group is taking, what you can do and why this is great news for devs from front to back. We may even talk about Michael Jackson Script, because, why not. Come join us and bring your questions :)

## Participant(s)

* Dan Shaw - @dshaw - Strategic Advisor
* Tara Z. Manicsic - @tzmanics - Guest Host
* Myles Borins - @MylesBorins - Node TSC Director / Developer Advocate for Google Cloud 
* Jordan Harband - @ljharb - TC39 Member / Software Engineer for Airbnb
* C J Silverio - @ceejbot - CTO for npm

## Schedule

Live Tuesday, JUL 10, 2018 at 10am PT on Crowdcast
https://www.crowdcast.io/e/dshawaf6

## Agenda

The agenda will evolve as we lock in panelists.

*Part I: How We Got Here*
- the creation of the common js modules system
- how es modules came to be

*Part II: Adapting to Interop*
- the challenges
- michael jackson script decision
- the role of compilers

*Part III: Where Are We Now?* 
- goals for the Modules Working Group
- how can devs participate/help

## Transcript

Not available

## Link(s)

* [Woebot](https://woebot.io/?r=dshawaf) - Mental health impacts us all. [https://woebot.io/jobs](https://woebot.io/jobs).

## Meta

#dshawaf #AlwaysForward #nodejs

**Comment by dshaw** [comment]
RSVP: https://www.crowdcast.io/e/dshawaf6

**Comment by MylesBorins** [comment]
I'm available

**Comment by ljharb** [comment]
I should be able to make it.

**Comment by dshaw** [comment]
@ceejbot is interested too

**Comment by dshaw** [comment]
![dshawaf6-cover](https://user-images.githubusercontent.com/4322/42032975-9e79eef4-7adb-11e8-82f0-83cd37d987db.jpg)

<3 this. Way better than the rando Unsplash images I have been using. Thank you, @tzmanics.
