### ISSUE TITLE
Dev Related on HTTP/2

### ISSUE THREAD

**Issue by dshaw** [dshaw/alwaysforward#20]
## Title

Always Forward with dshaw: Dev Related on HTTP/2

## Topic

HTTP/2, the artist formerly known as SPDY, is now available in Node.js in the latest versions (9, 10). We'll explore with our esteemed panelists the impact and potential of native HTTP/2 support.

## Participant(s)

* Anatoli Papirovski - @apapirovski 
* Anna Henningsen - @addaleax 
* James Snell - @jasnell
* Tara Manicsic - @tzmanics - Guest Host

## Schedule

Tuesday, SEP 11, 2018 at 10am PT on [Crowdcast](https://www.crowdcast.io/e/dshawaf8).

## Agenda

__Panelist Intros ~:00__

__Part I: The Journey to HTTP/2 ~:05__

- What is history of HTTP/1 to HTTP/2 (James)
- Implementation from HTTP/1 to HTTP/2 (Anna)
- The path to passing tests in HTTP/2 (Anatoli)

*Sponsor Spot ~:20*

__Part II: The Dev’s Journey to HTTP/2 ~:22__

- What is the best way for users to transition to HTTP/2?
- What about the compatibility mode? (Anatoli)
- What parts of the new API are you most excited for Dev’s to take advantage of?
- What performance improvements are most worth noting?

__Part III: What’s Next  & Audience Questions  ~:37__

- What improvements would you like to see next?
- What is the special API to deal with files and how can it be improved in time? (Anna)
- <Audience questions & any questions from Twitter>

*Sponsor Spot ~:52*

__Panelist Picks or Shoutouts  ~:54__

*Optional Topics*
- How does `server push` work?
- What capabilities do multiplexing and push streams bring to Node?

## Transcript

Not available

## Link(s)

* 

## Meta

#dshawaf #AlwaysForward #nodejs

**Comment by addaleax** [comment]
Yay! I should have better availability this time than for the last invitation – sorry again for that.

If you’re looking at core devs to talk to, https://github.com/apapirovski is another excellent choice (the most active dev in the area over the last 3 months).

**Comment by jasnell** [comment]
Works for me! When you thinking?

**Comment by tzmanics** [comment]
@jasnell this episode would be on Tuesday Sept 11 at 10a ET

**Comment by dshaw** [comment]
@apapirovski Would you like to join us?

**Comment by apapirovski** [comment]
@dshaw would love to.
