### ISSUE TITLE
[#dshawaf5] Architect's View on Frameworks versus Reference Implementations

### ISSUE THREAD

**Issue by dshaw** [dshaw/alwaysforward#9]
## Title

Architect's View on Frameworks versus Reference Implementations

## Topic

The role of the Software Architect is to align a company on the best practices for building software at a company. Most Architects are not coding in their day-to-day. When Waterfall development was prevalent, this often meant creating UML documents and high-level architecture design docs and requirements.

Today, the primary tools for aligning how fast-moving teams create applications are internal frameworks or reference implementations. We will explore what works and what doesn't work.

## Participant(s)

* Dan Shaw - @dshaw
* Ahmad Nassri - @ahmadnassri
* Aaron Heckmann - @aheckmann
* Joel Chen - @jchip
* Tara Z. Manicsic - @tzmanics

CANDIDATES
* Trevor Livingston - @tlivings [💁‍♂️ @dshaw]

## Schedule
Tuesday, JUN 12, 2018 at 10am PT on [Crowdcast](https://www.crowdcast.io/e/dshawaf5).

## Agenda

**Part I (15min) on being a Software Architect**
- how would you describe a SA
- what does day-to-day look like at your company
- what best practices or standards do you stick to
- when does the developer's view come into play (Ahmad)

_(sponsor spot)_

**Part II (15min) on Frameworks**
- how have you made choices between frameworks (Joel)
- what choices do you make regarding to opensource or licensed (Joel)
- contributing to opensource (Ahmad)

**Part III  (15min) on Reference Implementations**
- when would you prefer reference implementations

**Time for Questions from attendees**

## Transcript

Not available

## Link(s)

* [Woebot](https://woebot.io/?r=dshawaf) - Mental health impacts us all. [https://woebot.io/jobs](https://woebot.io/jobs).

## Meta

#dshawaf5 #dshawaf #AlwaysForward #ArchitectsView  #nodejs #nodesummit #operationcode #woebot

**Comment by ahmadnassri** [comment]
Interesting note on the "architects are not coding", I think that depends on the company and the business, more thoughts here: https://medium.com/@ahmadnassri/what-is-a-software-architect-and-should-they-write-code-fc1fb598c3b4

**Comment by dshaw** [comment]
@ahmadnassri Thank you for sharing the context. Sounds to me like you're volunteering to do the 10 minute preso for this one. 😜

**Comment by ahmadnassri** [comment]
@dshaw depends on final date, May is too busy ;)

**Comment by dshaw** [comment]
June, then. 👍

**Comment by dshaw** [comment]
@aheckmann Can I count you in for 6/12?

**Comment by dshaw** [comment]
@jchip Interested in sparing with @ahmadnassri on this one on Tuesday, June 12th?

**Comment by jchip** [comment]
@dshaw yup, I can do that.  thanks.
